### ISSUE TITLE
could you explain uvOffset ? 

### ISSUE THREAD

**Issue by Neovariance** [MajorStorm/Planetary-Terrain#2]
In MeshGenerator :

In the constructor we have : 
`uvOffset = 2.0 * new Vector3Double(callerNode.uv.x, 0, callerNode.uv.y);`

and then in SphereizedPos 

`Vector3Double planePos = new Vector3Double(x * vertexPosScale - scale, 1, z * vertexPosScale - scale) + uvOffset;
`

If I don't use UV at all ( triplanar / shader generated colors)  , can I get rid of uvOffset too ?

**Comment by josephhd** [comment]
The uvOffset is a descriptor of the chunk position on a unit plane (1x1). Before the quad sphere is, sphereized, it is composed of 6 planes. Each plane is a unit plane. When a chunk splits, the positions of each node needs to be stored, this is the uvOffset. It is not for textures, and is critical for the meshes to be built correctly. I believe that the center of each chunk on this imaginary unit plane is stored.
