### ISSUE TITLE
No colliders culling

### ISSUE THREAD

**Issue by Neovariance** [MajorStorm/Planetary-Terrain#4]
Colliders of the highest subdivision level are not needed. 
Colliders away from the player should probably be deactivated.

This could be a huge performance problem if the bounding boxes of the different chunks mesh colliders intersect - and due to the spherical nature it seems to me they do intersect ! Maybe just setting a physics layer that doesn't self intersect would be a huge improvement !

**Comment by josephhd** [comment]
Yes I agree, not every collider should be activated. Honestly, I never got to this, and I think there is probably an even better way to do this with ECS, Jobs, and the new scriptable render pipeline (this is another reason I haven't really worked on this project). 

As far as mesh collider intersections, that is a really good point and I will definitely keep that in mind. I agree that a physics layer tweak would be a nice way to do it.

**Comment by Neovariance** [comment]
:) I actually want to modify the code to use the new unity 2018 jobs and unity mathematics - adding double vector types is on their todo list.
